# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

permalink: /:year/:month/:day/:title.html
paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: rouge
markdown: kramdown

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: "雨は、いつか上がるのかな"

description: Myyura
# gavatar头像及Favicon
gavatar: https://myyura.github.io/assets/ico/kurosakura.jpg
favicon: 

author:
  name: Myyura
  email: zz940521@gmail.com
  github: Myyura
  bio: 愛と妄執を積み重ねて、幾星霜、世界はいつでも哀しみに満ちている。

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

#BASE_PATH:
BASE_PATH: https://myyura.github.io/

#gitalk
gitalk_owner: myyura 
gitalk_repo: myyura.github.io
gitalk_client_id: 16a06d873b585c32ddae
gitalk_client_secret: d71f669579791d1500ad8e1713e53ad10fa4149e
